set APPDATA=C:\Users\brian\AppData\Roaming
set ARCH=64
set CLIENTNAME=FENRIR
set CMAKE_GENERATOR=Visual Studio 14 2015 Win64
set CommandPromptType=Native
set CommonProgramFiles=C:\Program Files\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-VPIDHUR
set ComSpec=C:\WINDOWS\system32\cmd.exe
set CONDA_BUILD=1
set CONDA_DEFAULT_ENV=C:\Users\brian\Anaconda3\envs\_build
set CONDA_LUA=5.2
set CONDA_NPY=None
set CONDA_PATH_BACKUP=C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\brian\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Users\brian\Anaconda3;C:\Users\brian\Anaconda3\Scripts;C:\Users\brian\Anaconda3\Library\bin;C:\Users\brian\AppData\Local\Microsoft\WindowsApps;
set CONDA_PERL=5.18.2
set CONDA_PY=35
set CONDA_R=3.2.2
set CONDA_ROOT=C:\Users\brian\Anaconda3
set CPU_COUNT=8
set CYGWIN_PREFIX=/cygdrive/c/Users/brian/Anaconda3/envs/_build
set ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
set Framework40Version=v4.0
set FrameworkDir=C:\Windows\Microsoft.NET\Framework64
set FrameworkDIR64=C:\Windows\Microsoft.NET\Framework64
set FrameworkVersion=v4.0.30319
set FrameworkVersion64=v4.0.30319
set GIT_BUILD_STR=1922_g91e68db
set GIT_DESCRIBE_HASH=g91e68db
set GIT_DESCRIBE_NUMBER=1922
set GIT_DESCRIBE_TAG=KnimeNodes_Dec2014_Binary
set GIT_FULL_HASH=91e68db827f0e00bbd07c327a1c4a75f6955fb6f
set HOMEDRIVE=C:
set HOMEPATH=\Users\brian
set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt;C:\Users\brian\Anaconda3\envs\_build\Library\include;
set LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\um\x64;C:\Users\brian\Anaconda3\envs\_build\Library\lib;
set LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
set LIBRARY_BIN=C:\Users\brian\Anaconda3\envs\_build\Library\bin
set LIBRARY_INC=C:\Users\brian\Anaconda3\envs\_build\Library\include
set LIBRARY_LIB=C:\Users\brian\Anaconda3\envs\_build\Library\lib
set LIBRARY_PREFIX=C:\Users\brian\Anaconda3\envs\_build\Library
set LOCALAPPDATA=C:\Users\brian\AppData\Local
set LOGONSERVER=\\DESKTOP-VPIDHUR
set LUA=C:\Users\brian\Anaconda3\envs\_build\lua.exe
set LUA_INCLUDE_DIR=C:\Users\brian\Anaconda3\envs\_build\include
set LUA_VER=5.2
set MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out;
set MSYS2_ENV_CONV_EXCL=CL
set NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
set NUMBER_OF_PROCESSORS=8
set OculusBase=C:\Program Files\Oculus\
set OS=Windows_NT
set Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Users\brian\Anaconda3\envs\_build;C:\Users\brian\Anaconda3\envs\_build\Library\bin;C:\Users\brian\Anaconda3\envs\_build\Scripts;C:\Users\brian\Anaconda3\envs\_build;C:\Users\brian\Anaconda3\envs\_build\Library\bin;C:\Users\brian\Anaconda3\envs\_build\Scripts;C:\Users\brian\Anaconda3\Library\bin;C:\Users\brian\Anaconda3\Library\bin;C:\Users\brian\Anaconda3;C:\Users\brian\Anaconda3\Scripts;C:\Users\brian\Anaconda3\Library\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\brian\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Users\brian\AppData\Local\Microsoft\WindowsApps
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PERL_VER=5.18.2
set PKG_BUILDNUM=1
set PKG_BUILD_STRING=np111py35_1
set PKG_NAME=rdkit
set PKG_VERSION=__conda_version__
set Platform=X64
set PREFIX=C:\Users\brian\Anaconda3\envs\_build
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=5e03
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=[Anaconda3] $P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set PY3K=1
set PYTHON=C:\Users\brian\Anaconda3\envs\_build\python.exe
set PYTHONNOUSERSITE=1
set PYTHON_LIBRARY=python35.lib
set PY_VER=3.5
set R=C:\Users\brian\Anaconda3\envs\_build\Scripts\R.exe
set RECIPE_DIR=C:\Users\brian\devel\conda-rdkit\rdkit
set SCRIPTS=C:\Users\brian\Anaconda3\envs\_build\Scripts
set SESSIONNAME=RDP-Tcp#2
set SP_DIR=C:\Users\brian\Anaconda3\envs\_build\Lib\site-packages
set SRC_DIR=C:\Users\brian\Anaconda3\conda-bld\work
set STDLIB_DIR=C:\Users\brian\Anaconda3\envs\_build\Lib
set SystemDrive=C:
set SystemRoot=C:\WINDOWS
set SYS_PREFIX=C:\Users\brian\Anaconda3
set SYS_PYTHON=C:\Users\brian\Anaconda3\python.exe
set TEMP=C:\Users\brian\AppData\Local\Temp
set TMP=C:\Users\brian\AppData\Local\Temp
set UCRTVersion=10.0.10586.0
set UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
set USERDOMAIN=DESKTOP-VPIDHUR
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-VPIDHUR
set USERNAME=brian
set USERPROFILE=C:\Users\brian
set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
set VisualStudioVersion=14.0
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\
set VS_MAJOR=14
set VS_VERSION=14.0
set VS_YEAR=2015
set windir=C:\WINDOWS
set WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References
set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
set WindowsSDKLibVersion=10.0.10586.0\
set WindowsSDKVersion=10.0.10586.0\
set WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
set WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\

set RDBASE=C:\Users\brian\Anaconda3\conda-bld\work
set PYTHONPATH=%RDBASE%

ctest -R pyChemReactions -VV

