package:
  name: rdkit
  version: 2016.4.5

source:
  #git_url: https://github.com/rdkit/rdkit.git
  #git_tag: Release_2016_03_4
  path: c:/Users/brian/devel/bp-rdkit
  patches:
    - rdpaths.patch
  #  - rdconfig.patch [win]

build:
  number: 1

requirements:
  build:
    - cmake
    - requests
    - boost ==1.56.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - python
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.11') }}
    - pillow
    - freetype
    - cairocffi [linux]
    - pandas
  run:
    - boost ==1.56.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - python
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.11') }}

test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
